# Use the official Node.js image as the base image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json tsconfig.json ./
COPY prisma/ ./prisma/
COPY src/ ./src/
COPY .env ./

# Install system-level dependencies and tools
RUN apt-get update && apt-get install -y \
  curl \
  && rm -rf /var/lib/apt/lists/*

# Install pnpm globally
RUN npm i -g npm@latest pnpm

# Set the environment variables
ENV PNPM_HOME /usr/local/share/pnpm
ENV PATH $PNPM_HOME:$PATH

# Install global packages
RUN pnpm add -g pm2 @nestjs/cli

# Install project dependencies
RUN pnpm install

# Expose the port your Nest.js application is running on
EXPOSE 3000

# Start the Nest.js application
CMD ["pnpm", "run", "start:dev"]
