version: '3'
services:
  backend:
    build:
      dockerfile: 'Dockerfile.dev'
      context: 'services/backend'
    ports:
      - "3000:3000"
    depends_on:
      - database  # This ensures the 'database' service starts before 'backend'
    environment:
      DATABASE_HOST: database  # Use the service name as the hostname
      DATABASE_PORT: 5432
      DATABASE_NAME: sofit-db
      DATABASE_USER: sofit
      DATABASE_PASSWORD: sofitadmin
    volumes:
      - ./services/backend/src:/app/src

  frontend:
    build:
      dockerfile: 'Dockerfile.dev'
      context: 'services/frontend'
    ports:
      - "4200:4200"
    volumes:
      - ./services/frontend/src:/app/src
  
  database:
    hostname: sofit-db
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=sofit
      - POSTGRES_PASSWORD=sofitadmin
    volumes:
      - ./local-data/postgres:/data/postgres
    ports:
      - '5432:5432'