# Use the official Node.js image as the base image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json tsconfig.json ./
COPY src/ ./src/
COPY .env.local ./

# Install global packages and dependencies
RUN npm install -g @nrwl/cli

# Install pnpm globally
RUN npm i -g npm@latest pnpm

# Install project dependencies
RUN pnpm install

RUN nx g add shared-ui

# Expose the port your application is running on (if needed)
EXPOSE 4200

# Start your application
CMD ["pnpm", "dev"]
